### ISSUE TITLE
Format On Save triggers infinite loop for JSON documents

### ISSUE THREAD

**Issue by ddotlic** [SamVerschueren/vscode-final-newline#11]
- VSCode Version: 1.6.0 insider (Oct 1 2016)
- OS Version: macOS Sierra

Steps to Reproduce:
1.  set `"editor.formatOnSave": true` somewhere (in my case, user settings)
2. open JSON file
3. edit the file
4. try to save the file, note that CPU spikes and VS Code clearly runs in a loop saving, reformatting, saving, reformatting... ad nauseam; the only way to stop this is to close the file; additionally, when I do, it's clear that this extension has not been executed 

When I deactivate the extensions things work fine.

Note that the type of document is important - for JavaScript documents things work like a charm.

While I definitely expect the VS Code team to add the feature this extension implements into the core product, I'm not holding my breath - could you please fix this?

Very likely the issue is with the way the document saving has been done now - please see https://github.com/Microsoft/vscode/pull/12454 and https://github.com/Microsoft/vscode/issues/239

**Comment by SamVerschueren** [comment]
I don't have a `editor.formatOnSave` setting, is that an extension as well?

**Comment by SamVerschueren** [comment]
Alright, noticed you where using the insiders build. This indeed is a bug. The reason is that `formatOnSave` removes the final new line. My extension adds it again, does another save and triggers the formatting again which removes it. This causes an infinite loop. Will release an update once the insider version gets released.

**Comment by ddotlic** [comment]
Sorry for not making it more obvious that the setting is newly introduced and only those with insider see it (therefore not many will experience this bug).

Luckily for me (assuming you have time in the near future) the new version should come out in a few days 😄 There was quite a bit of chatter regarding exactly this situation - in which order are extensions (and core) executed while saving? In your case seeing how auto format kills the last newline (it's insane) it would be imperative that your extension executes later. Ideal would be for auto-format to add the last new line itself, but like I said for some silly reason this "feature" is not important enough at the moment.

**Comment by SamVerschueren** [comment]
Will be released with the next VS Code release.

**Comment by ddotlic** [comment]
@SamVerschueren LOL, you've already fixed it 👍 

I wanted to ask "why not release it now" but it depends on the new API thus has to wait.

🎉 cheers!

**Comment by SamVerschueren** [comment]
I have to clue if the [engines](https://github.com/SamVerschueren/vscode-final-newline/blob/master/package.json#L7) field actually does anything. Like, does it prevent from installing the extension in older version? I have been thinking and searching for that for quite some time.

Maybe, let's just ask :p.

@bpasero @jrieken Does the [engines](https://github.com/SamVerschueren/vscode-final-newline/blob/master/package.json#L7) field prevent an extension from being installed in older versions? If I'm not mistaken, this wasn't the case.

**Comment by jrieken** [comment]
> Does the engines field prevent an extension from being installed in older versions? If I'm not mistaken, this wasn't the case.

It should but @joaomoreno will know for sure

**Comment by ddotlic** [comment]
It would be nice if publishing an extension with a version newer than the current version would not only prevent people using "stable" from installing it but also allow insiders to do so 😄 (assuming insider matches the newly published version yet "stable" doesn't)

One can hope...

**Comment by SamVerschueren** [comment]
So it would be safe to release the extension right now with engines field being set to `^1.6.x`?

@jrieken Thanks for chiming in on this! 🍻

**Comment by joaomoreno** [comment]
@SamVerschueren 👍

**Comment by SamVerschueren** [comment]
@joaomoreno Thanks for confirming!

@ddotlic Released as `0.3.0`. Not sure if the insider build picks this up though :).

**Comment by ddotlic** [comment]
@SamVerschueren Thanks for the push, but the insider build is not picking it up for the moment.

@joaomoreno Is this a supported scenario? How can I be sure that Insider (if it's possible) has checked for outdated extensions (I've tried obvious things like using the commands which mention "outdated", "update extensions" and I've tried restarting the app)?

**Comment by joaomoreno** [comment]
Code will often refresh information from the Marketplace to know which extensions are outdated. That information is also refreshed for an extension if you simply search for it in Code.

**Comment by ddotlic** [comment]
> That information is also refreshed for an extension if you simply search for it in Code.

@joaomoreno That did it, thanks! I think there has to be a better way to do this though 😉 

@SamVerschueren Installed and works like a charm! 🍾 Thanks!

**Comment by SamVerschueren** [comment]
@joaomoreno That worked! The insider build found the extension and installed it. However, there seems to be a bug because of that `engines` field. My current VS Code installation (1.5.3), which doesn't fall into the accepted range (^1.6.x), I get a notification for an update. Clicking on it however, seems to install it but after clicking `enable`, it restarts and notifies me that `final-newline` has a new update. So updating it doesn't work (which is good), but the notification stays. If you want I can create a new issue in the vscode repo. Let me know.

**Comment by SamVerschueren** [comment]
>  I think there has to be a better way to do this though

Nah, it would be pointless to do constant polling of the marketplace for outdated extensions. Most of the times you don't care if you get a notification straight away or just a couple of hours later.

**Comment by ddotlic** [comment]
@SamVerschueren I meant rather an explicit way to check for outdated extensions. Bizarrely, though I get the notifications when I restart Code, this time it worked only when I searched for the extension. No matter, it's not a big issue, waiting a few hours is just fine in general case.

**Comment by joaomoreno** [comment]
@SamVerschueren That issue is known and the fix (already in `master`) comes in 1.6. 👍  Thanks, though!

**Comment by joaomoreno** [comment]
@ddotlic You are not alone. Microsoft/vscode#12909

**Comment by ddotlic** [comment]
@joaomoreno You people are faster than light - you rock! 🎸

**Comment by SamVerschueren** [comment]
@joaomoreno Did you mean this https://github.com/Microsoft/vscode/issues/13303? Or where you referring to @ddotlic?
