### ISSUE TITLE
Strange vscode update issue

### ISSUE THREAD

**Issue by J-Siu** [SamVerschueren/vscode-final-newline#14]
I see your package is available for update in vscode today and click it. However, after vscode restart it will remain in 0.2.0 and ask for update again.

![screen shot 2016-10-06 at 21 21 01](https://cloud.githubusercontent.com/assets/3171920/19176162/336a7a9a-8c0b-11e6-9f65-f93dfac6d8d7.png)

Not sure how to debug the issue.

**Comment by SamVerschueren** [comment]
#13 

Keeping this open for discovery.

**Comment by rimselis** [comment]
Having same issue.
Removal and install did not help.

**Comment by SamVerschueren** [comment]
Please read through the comments. It's a bug in VS Code and `final-newline@0.3.0` shouldn't be installable in VS Code 1.5.

**Comment by gluons** [comment]
**0.3.0**'s `engine` is [`^1.6.x`](https://github.com/SamVerschueren/vscode-final-newline/blob/v0.3.0/package.json#L7).

So, we can't install 0.3.0 in current VSCode. Current latest version is **[1.5.3](https://code.visualstudio.com/updates/v1_5#_153-fully-translated-build)** .

Owner explained in #13.

> You shouldn't be able to. `final-newline@0.3.0` uses the new API which is now in the Insiders Build and will be released with the next VS Code release in a couple of days. That version fixes #8 and #11. The reason you are seeing this update is due to a bug Microsoft/vscode#13303 because `final-newline@0.3.0` is targetted to VS Code [^1.6.x](https://github.com/SamVerschueren/vscode-final-newline/blob/master/package.json#L7).

**Comment by gluons** [comment]
Now, VSCode has released [1.6](https://code.visualstudio.com/updates/v1_6). This issue is solved.

**Comment by SamVerschueren** [comment]
I'm going to leave this open for a couple more days. Not everyone upgrades their software immediately.
