### ISSUE TITLE
Trim multiple empty last lines

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/vscode-final-newline#15]
From the marketplace: https://marketplace.visualstudio.com/items?itemName=samverschueren.final-newline

> Does what it says - adds a missing new line.  I'll give 5 \* when there will be a config for trimming multiple empty lines down to single empty line at the end of file.

Seems like a nice addition but in a separate setting though. Some people might not want this.

**Comment by SavageCore** [comment]
Can be closed now as vscode has `files.trimFinalNewlines`

Edit: Hang on, this addon is deprecated entirely by `files.insertFinalNewline`! Should probably update readme like https://github.com/jmlntw/vscode-ensure-single-final-newline

**Comment by SamVerschueren** [comment]
You're right, thanks :)
