### ISSUE TITLE
Cursor moves if it's at the end of the last line

### ISSUE THREAD

**Issue by anders-advisa** [SamVerschueren/vscode-final-newline#9]
This is a bit annoying when you have auto save on and start typing on the first line of an empty file.

When it saves, the cursor will move down to the newly created empty line

**Comment by SamVerschueren** [comment]
Thanks for the report. I'm aware of the bug, but I believe I can't do anything about it as long as this issue in VSCode isn't resolved https://github.com/Microsoft/vscode/issues/4802.

If you have any ideas on how to tackle the problem, feel free to post suggestions.

---

EditorConfig has the same problem https://github.com/editorconfig/editorconfig-vscode/issues/40

**Comment by sudoforge** [comment]
Is it possible to move the cursor back to the previous position -- immediately after adding the new line? I have not looked into VSCode's extension API at all, so perhaps this is an obvious impossibility, but just a thought as a (hopefully temporary) workaround.

**Comment by SamVerschueren** [comment]
I recorded what it would look and you'll notice a flicker (only if the current position is the last position in the file).

![cursor-position](https://cloud.githubusercontent.com/assets/1913805/19339370/5398ef00-9123-11e6-9d3f-d147625a6076.gif)

**Comment by sudoforge** [comment]
Hm, well I certainly can't speak for all of the users of your extension, but it would seem like that, while not an ideal fix, would be more satisfactory than having to manually adjust the cursor position.

**Comment by SamVerschueren** [comment]
I guess you are right. This probably won't be fixed in the near time in VS Code itself so better have a less ideal workaround for now. Fixed in `0.3.1`.
